### PR TITLE
adding the notebook for soical econ geo analysis

### PR DESCRIPTION
**Pull request by RNAer**

### CODE REVIEW

**Comment by wasade** [comment]
Would it be possible to add in references (and licenses as appropriate) for where the data came from? For instance, "SAIPESNC_25OCT17_19_27_20_88.csv"

**Comment by RNAer** [comment]
updated

**Comment by wasade** [comment]
Thanks! Would it be possible to move all this to under an analysis specific sub directory of `ipynb`?

**Comment by wasade** [comment]
@RNAer ping on the file movement comment otherwise good to merge

**Comment by RNAer** [comment]
@wasade , moved.

**Comment by wasade** [comment]
Thanks!

**Pull request merged**
