### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by afvrbanac**
Heatmap notebook and yml file of conda environment. Let me know if I need to edit anything!

### CODE REVIEW

**Comment by wasade** [comment]
Great, thank you! Would it be possible to move the notebook to under the ipynb directory (e.g., `git mv AG_World_Heatmap.ipynb ipynb/`?

**Comment by afvrbanac** [comment]
Whoops sorry, I moved it. Do you also want the yml file or should I delete that (or move it to the env folder?)

**Comment by wasade** [comment]
Env please, thanks!

**Comment by afvrbanac** [comment]
Done! Woo first pull request

**Comment by wasade** [comment]
:boom:

**Pull request merged**
