### PR TITLE
First draft of AGP trading cards

### PR DESCRIPTION
**Pull request by cuttlefishh**
Still working through a few issues with plots and wikipedia and choosing best sequences to display. Core functionality is there, however.

### CODE REVIEW

**Comment by wasade** [comment]
Good to merge?

**Comment by cuttlefishh** [comment]
The figure is in final form. Good to merge!

**Comment by cuttlefishh** [comment]
@wasade, should we merge?

**Comment by wasade** [comment]
Ya can you?

**Comment by cuttlefishh** [comment]
Don't got write access to this repo.

**Comment by wasade** [comment]
Ah,a critical detail...

**Pull request merged**
